### ISSUE TITLE
Assertion error with per4m/perf2trace.py at line 267

### ISSUE THREAD

**Issue by NGUETOUM** [maartenbreddels/per4m#5]
Hello, 
I have tried recently to use your tool per4m with viztracer to instrumentalize and trace the python GIL on my Ubuntu 20.04 operating system, but during the execution of python script, I have met an assertion error with perf2trace.py.

Before to execute the script I have followed all the instructions describe at this page: https://www.maartenbreddels.com/perf/jupyter/python/tracing/gil/2021/01/14/Tracing-the-Python-GIL.html

So, I have started to execute the following commands:

**$ sudo sysctl kernel.perf_event_paranoid=-1
$ sudo mount -o remount,mode=755 /sys/kernel/debug
$ sudo mount -o remount,mode=755 /sys/kernel/debug/tracing**

After this, I have also installed the python user space probes with the following commands:
**sudo perf probe -f -x `which python` python:take_gil=take_gil
sudo perf probe -f -x `which python` python:take_gil=take_gil%return
sudo perf probe -f -x `which python` python:drop_gil=drop_gil
sudo perf probe -f -x `which python` python:drop_gil=drop_gil%return
sudo perf probe -f -x /per4m/build/lib.linux-x86_64-3.8/per4m/pytrace.cpython-38-x86_64-linux-gnu.so pytrace:function_entry=pytrace_function_entry filename=filename:string funcname=funcname:string l=lineno what=what
sudo perf probe -f -x /per4m/build/lib.linux-x86_64-3.8/per4m/pytrace.cpython-38-x86_64-linux-gnu.so pytrace:function_return=pytrace_function_return**

Where lib.linux-x86_64-3.8 is the shared library obtained after build the initial project after cloning on GitHub.

The perf tool is executed normally when I run this command:
**perf record -e sched:sched_switch  -e sched:sched_process_fork -e 'sched:sched_wak*' -e python:take_gil -e python:take_gil__return -e python:drop_gil -e python:drop_gil__return -e pytrace:function_entry -e pytrace:function_return  -k CLOCK_MONOTONIC -- viztracer  -o viztracer1-uprobes.json --ignore_frozen -m example_3**

The issue come when I try to run this command:

**perf script --no-inline | per4m perf2trace gil -o perf1-uprobes.json**

I got this error:

**_Anomaly: this PIDs drops the GIL: 16934, but never took it (maybe we missed it?)
error on line        viztracer 16934 [000] 11628.254396:           python:drop_gil__return: (68e5b0 <- 7f414166fcb0)
Traceback (most recent call last):
  File "/usr/local/bin/per4m", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/per4m/__main__.py", line 28, in main
    main([os.path.basename(args[0]) + " " + args[1]] + args[2:])
  File "/usr/local/lib/python3.8/dist-packages/per4m/perf2trace.py", line 112, in main
    for header, event in gil2trace(sys.stdin, verbose=verbose, as_async=args.as_async, only_lock=args.only_lock, pids=pids):
  File "/usr/local/lib/python3.8/dist-packages/per4m/perf2trace.py", line 267, in gil2trace
    assert time_gil_take >= wants_take_gil[pid], f"{time_gil_take} >= {wants_take_gil[pid]}"
AssertionError: 11625901160.0 >= 11626145740.0_**

I don't know what cause this issue. Please, could you help me to solve this issue ?

Python :  3.8
Linux kernel: 5.11.0
perf : perf version of Linux 5.11.0 compile from source with make and copied into /usr/bin
viztracer: 0.15.6

**Comment by maartenbreddels** [comment]
It seems that we fail to catch the take_gil. What you could do is use the same Python (3.7) from conda-forge as I did. I think these things depend on how they are compiled.
If you manage to reproduce it, please share here how you've done it!

**Comment by NGUETOUM** [comment]
Ok, and thanks for the reply.
